In [1]:
#Normalization - Euclidean

from scipy.spatial.distance import euclidean
import numpy as np
import seaborn as sns

# Load the Iris dataset
df = sns.load_dataset("iris")
x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].to_numpy()

def compute_dissimilarity_matrix(x):
    n = len(x)
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            matrix[i][j] = euclidean(x[i], x[j])
    return matrix

# Compute the dissimilarity matrix
matrix = compute_dissimilarity_matrix(x)
print(matrix)


[[0.         0.53851648 0.50990195 ... 4.45982062 4.65080638 4.14004831]
 [0.53851648 0.         0.3        ... 4.49888875 4.71805044 4.15331193]
 [0.50990195 0.3        0.         ... 4.66154481 4.84871117 4.29883705]
 ...
 [4.45982062 4.49888875 4.66154481 ... 0.         0.6164414  0.64031242]
 [4.65080638 4.71805044 4.84871117 ... 0.6164414  0.         0.76811457]
 [4.14004831 4.15331193 4.29883705 ... 0.64031242 0.76811457 0.        ]]


In [2]:
import seaborn as sns
import numpy as np

iris=sns.load_dataset("iris")
x=iris.iloc[:,:-1]
print(x)
y=iris.iloc[:,-1]
print(y)

#1-Max Normalization
max1=x/(np.max(x,axis=0))
print("\n Max N:\n\n",max1)

#2-Min Max Normalization
min_max=(x-np.min(x,axis=0))/(np.max(x,axis=0)-np.min(x,axis=0))
print("\n Min Max N:\n\n",min_max)

#3-Upper Lower Normalization
u=20
l=10
max2=((x-np.min(x,axis=0))/(np.max(x,axis=0))*(u-l)+l)
print("\n Upper Lower N:\n\n",max2)

#Z-Score Normalization
z_score=(x-np.mean(x,axis=0))/(np.std(x,axis=0))
print("\n Z-Score N:\n\n",z_score)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

 Max N:

      sepal_length  sepal_width  petal_le

In [3]:
##Compute Dissimilarity matrix for the given Pattern matrix

from scipy.spatial.distance import euclidean
import numpy as np

# Generate random matrix x with values between 0 and 3
x = np.random.randint(0, 4, size=(5, 4), dtype=int)
print(x, "\n")

def compute_dissimilarity_matrix(x):
    n = len(x)
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            matrix[i][j] = euclidean(x[i], x[j])  # Calculate the Euclidean distance
    return matrix

# Compute the dissimilarity matrix
matrix = compute_dissimilarity_matrix(x)
print(matrix)


[[2 1 1 3]
 [3 3 0 2]
 [0 0 2 1]
 [1 3 2 3]
 [3 3 0 1]] 

[[0.         2.64575131 3.16227766 2.44948974 3.16227766]
 [2.64575131 0.         4.79583152 3.         1.        ]
 [3.16227766 4.79583152 0.         3.74165739 4.69041576]
 [2.44948974 3.         3.74165739 0.         3.46410162]
 [3.16227766 1.         4.69041576 3.46410162 0.        ]]


In [4]:
#Jaccards - 1.Binary

import numpy as np
from sklearn.metrics import jaccard_score

# Input matrix
x = np.array([[1, 0, 1, 1],
              [1, 1, 1, 0],
              [1, 1, 1, 0],
              [0, 0, 0, 1]])

def compute_jaccard_similarity_matrix(x):
    n = len(x)
    matrix = np.zeros((n, n))
    
    # Calculate Jaccard similarity between each pair of rows
    for i in range(n):
        for j in range(n):
            # We need to ensure both x[i] and x[j] are flattened (1D)
            matrix[i][j] = jaccard_score(x[i], x[j])  # This computes Jaccard similarity directly
    
    return matrix

# Compute the Jaccard similarity matrix
matrix = compute_jaccard_similarity_matrix(x)
print(matrix)


[[1.         0.5        0.5        0.33333333]
 [0.5        1.         1.         0.        ]
 [0.5        1.         1.         0.        ]
 [0.33333333 0.         0.         1.        ]]


In [5]:
#Jaccards - 3.Not Binary

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Input matrix
x = np.array([[3,2,5,4],
              [2,3,4,5]])
print(x,"\n")

def compute_similarity_matrix(x):
    n = len(x)
    matrix = np.zeros((x.shape[0],x.shape[0]))
    
    # Calculate Jaccard similarity between each pair of rows
    for i in range(n):
        for j in range(n):
            # We need to ensure both x[i] and x[j] are flattened (1D)
            matrix[i,j] = cosine_similarity(x[i].reshape(1,-1), x[j].reshape(1,-1))
    return matrix

# Compute the Jaccard similarity matrix
similarity_matrix = compute_similarity_matrix(x)
print("Cosine Similarity matrix : ")
print(similarity_matrix)


[[3 2 5 4]
 [2 3 4 5]] 

Cosine Similarity matrix : 
[[1.         0.96296296]
 [0.96296296 1.        ]]


/tmp/ipykernel_12960/3241082090.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  matrix[i,j] = cosine_similarity(x[i].reshape(1,-1), x[j].reshape(1,-1))
/tmp/ipykernel_12960/3241082090.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  matrix[i,j] = cosine_similarity(x[i].reshape(1,-1), x[j].reshape(1,-1))
/tmp/ipykernel_12960/3241082090.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  matrix[i,j] = cosine_similarity(x[i].reshape(1,-1), x[j].reshape(1,-1)

In [6]:
#Jaccards - 3.Sets

import numpy as np
def compute_jaccards_similarity_matrix(sets):
    n=len(sets)
    matrix=np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            intersection=len(sets[i].intersection(sets[j]))
            union=len(sets[i].union(sets[j]))
            matrix[i,j]=intersection/union
    return matrix
sets=[{1,2,5,7},{2,3,5,8}]

similarity_matrix = compute_jaccards_similarity_matrix(sets)
print("jaccards_similarity : ")
print(similarity_matrix)



jaccards_similarity : 
[[1.         0.33333333]
 [0.33333333 1.        ]]


In [7]:
#Pearson

import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([5,4,3,2,1])

correlation_matrix=np.corrcoef(x,y)
pearson_r=correlation_matrix[0,1]
print("Pearson Correlation coefficient : ",pearson_r)

Pearson Correlation coefficient :  -0.9999999999999999
